<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-17T18:09:37 IST" name="Default suite" finished-at="2024-04-17T18:12:04 IST" duration-ms="147245">
    <groups>
    </groups>
    <test started-at="2024-04-17T18:09:37 IST" name="Default test" finished-at="2024-04-17T18:12:04 IST" duration-ms="147245">
      <class name="TestCase.LoginTestCase">
        <test-method is-config="true" signature="InshilizeDriver()[pri:0, instance:TestCase.LoginTestCase@72967906]" started-at="2024-04-17T18:09:37 IST" name="InshilizeDriver" finished-at="2024-04-17T18:10:46 IST" duration-ms="68796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InshilizeDriver -->
        <test-method signature="Loginuser(java.util.HashMap)[pri:0, instance:TestCase.LoginTestCase@72967906]" started-at="2024-04-17T18:10:46 IST" name="Loginuser" data-provider="LoginData" finished-at="2024-04-17T18:11:33 IST" duration-ms="47555" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Passwoard= Rishi@10089, Email=rishipatil1504@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Full-Fledged practice website for Automation Engineers] but found [Proxy element for: DefaultElementLocator 'By.xpath: (//h2[text()='Full-Fledged practice website for Automation Engineers'])[1]']]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Full-Fledged practice website for Automation Engineers] but found [Proxy element for: DefaultElementLocator 'By.xpath: (//h2[text()='Full-Fledged practice website for Automation Engineers'])[1]']
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at TestCase.LoginTestCase.Loginuser(LoginTestCase.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginuser -->
        <test-method signature="Loginuser(java.util.HashMap)[pri:0, instance:TestCase.LoginTestCase@72967906]" started-at="2024-04-17T18:11:33 IST" name="Loginuser" data-provider="LoginData" finished-at="2024-04-17T18:12:04 IST" duration-ms="30423" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Passwoard= Rishi@10089m, Email=rishipatil150a4@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Full-Fledged practice website for Automation Engineers] but found [Proxy element for: DefaultElementLocator 'By.xpath: (//h2[text()='Full-Fledged practice website for Automation Engineers'])[1]']]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Full-Fledged practice website for Automation Engineers] but found [Proxy element for: DefaultElementLocator 'By.xpath: (//h2[text()='Full-Fledged practice website for Automation Engineers'])[1]']
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at TestCase.LoginTestCase.Loginuser(LoginTestCase.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginuser -->
        <test-method is-config="true" signature="TerDown()[pri:0, instance:TestCase.LoginTestCase@72967906]" started-at="2024-04-17T18:12:04 IST" name="TerDown" finished-at="2024-04-17T18:12:04 IST" duration-ms="211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TerDown -->
      </class> <!-- TestCase.LoginTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
